# Alpha-Agent System Configuration Example

# API Keys (Replace with your own keys)
api_keys:
  openai: "your-openai-api-key"
  polygon: "your-polygon-api-key"

# System Configuration
system:
  update_interval: 60  # seconds
  evaluation_interval: 300  # seconds
  log_level: "INFO"
  cache_dir: "./cache"

# Data Configuration
data:
  default_tickers: ["SPY", "QQQ", "AAPL", "MSFT", "AMZN", "GOOGL", "META"]
  update_interval: 60  # seconds
  data_history_days: 7
  default_timespan: "hour"
  options_enabled: false
  news_limit: 100
  data_storage: "./data/market_data"

# Prediction Configuration
prediction:
  models:
    - name: "lstm"
      parameters:
        layers: 2
        units: 50
        dropout: 0.2
    - name: "transformer"
      parameters:
        heads: 8
        layers: 4
        dropout: 0.1

# Trading Configuration
trading:
  initial_capital: 100000
  position_size: 0.1
  risk_per_trade: 0.02
  signal_threshold: 0.7

# Risk Configuration
risk:
  max_drawdown: 0.2
  market_indices: ["SPY", "QQQ", "DIA"]

# Sentiment Configuration
sentiment:
  news_weight: 0.3
  social_weight: 0.7

# Output Configuration
output:
  results_dir: "results"
  plots_dir: "plots"
  report_format: "json"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# API Configuration
api:
  rate_limit: 5  # requests per second
  retry_attempts: 3
  retry_delay: 1  # seconds 